import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#6B3FA0',
  primaryLight: '#8F67B8',
  secondary: '#F5CAC3',
  textDark: '#333333',
  textMedium: '#555555',
  textLight: '#888888',
  grayLight: '#E5E5E5',
  grayMedium: '#A9A9A9',
  white: '#FFFFFF',
  border: '#DDDDDD',
  error: '#FF5252',
  success: '#4CAF50',
  background: '#F8F8F8',
  success: '#4CAF50',
  warning: '#FFC107',
  info: '#2196F3',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  headerContainer: {
    marginBottom: 24,
  },
  screenTitle: {
    fontSize: 28,
    fontFamily: 'Poppins-SemiBold',
    color: COLORS.primary,
    marginBottom: 8,
  },
  screenSubtitle: {
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textMedium,
  },
  sectionContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'Poppins-Medium',
    color: COLORS.textDark,
    marginBottom: 12,
  },
  sectionDescription: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textLight,
    marginBottom: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: COLORS.white,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    marginLeft: 8,
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: COLORS.textDark,
  },
  productList: {
    marginLeft: -5,
    marginRight: -5,
  },
  productListContent: {
    paddingHorizontal: 5,
  },
  productItem: {
    width: 120,
    borderRadius: 10,
    marginHorizontal: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
  },
  selectedProduct: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(107, 63, 160, 0.05)',
  },
  productImage: {
    width: '100%',
    height: 90,
    backgroundColor: COLORS.grayLight,
  },
  noImageContainer: {
    width: '100%',
    height: 90,
    backgroundColor: COLORS.grayLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productInfo: {
    padding: 8,
  },
  productName: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: COLORS.textDark,
  },
  productPrice: {
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textMedium,
    marginTop: 4,
  },
  checkmarkContainer: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedProductInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.grayLight,
  },
  selectedProductTitle: {
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    color: COLORS.textMedium,
    marginRight: 6,
  },
  selectedProductName: {
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    color: COLORS.primary,
    flex: 1,
  },
  emptyProductsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  emptyProductsText: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textLight,
    marginTop: 8,
  },
  loader: {
    marginVertical: 20,
  },
  priceInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  currencySymbol: {
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    color: COLORS.textMedium,
    marginRight: 6,
  },
  priceInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textDark,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    color: COLORS.textDark,
    marginBottom: 8,
    marginTop: 16,
  },
  requiredStar: {
    color: COLORS.error,
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: COLORS.white,
  },
  input: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textDark,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  characterCount: {
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
    color: COLORS.textLight,
    textAlign: 'right',
    marginTop: 4,
  },
  sendButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  disabledButton: {
    backgroundColor: COLORS.grayMedium,
    opacity: 0.7,
  },
  buttonIcon: {
    marginRight: 8,
  },
  sendButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
  },
});

export default styles;